services:
  - type: web
    name: Rankerbackend
    env: python
    region: oregon
    plan: free
    rootDir: SDGClassifier
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true
    envVars:
      - key: PORT
        value: 5000

  - type: web
    name: RankingYT
    env: node
    rootDir: SDGClassifier/client
    buildCommand: |
      npm install
      npm run build
    startCommand: npx serve -s build
    plan: free
    autoDeploy: true
