services:
  - type: web
    name: Rankerbackend
    env: python
    region: oregon
    plan: free
    rootDir: SDGClassifier
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true
    envVars:
      - key: PORT
        value: 5000

  - type: static
    name: RankingYT
    rootDir: SDGClassifier/client
    buildCommand: npm install && npm run build
    staticPublishPath: build
    autoDeploy: true
